// src/generate/generator.js
import { writeFileSync } from 'fs';
import { dirname, relative } from 'path';

export function generateHandlersFile(mockFiles, outputFile, includeMethods) {
  const imports = mockFiles.map((file) => {
    const relativePath = relative(dirname(outputFile), file.path)
      .replace(/\\/g, '/')
      .replace('.ts', '');

    return `import { ${file.functionNames.join(
      ', '
    )} } from '${relativePath}';`;
  });

  const allMockFunctions = mockFiles.flatMap((file) => file.functionNames);

  const content = `/**
 * Auto-generated file. Do not edit manually.
 * Generated at: ${new Date().toISOString()}
 * 
 * Included HTTP methods: ${includeMethods.join(', ').toUpperCase()}
 * Total endpoints: ${allMockFunctions.length}
 * 
 * Generated by @cy/msw-openapi-helper
 */

${imports.join('\n')}

export const handlers = [
${allMockFunctions.map((fn) => `  ...${fn}(),`).join('\n')}
];
`;

  writeFileSync(outputFile, content, 'utf-8');

  return {
    totalHandlers: allMockFunctions.length,
    totalFiles: mockFiles.length,
  };
}
